name = "HFDynamic"
uuid = "b98afb42-8d19-11e9-0754-43db704d0aa3"
authors = ["Patrick Grössing <invarianztheorem@web.de>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
